import { execFile } from "node:child_process";
import { mkdir, mkdtemp, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { promisify } from "node:util";
import { Octokit } from "@octokit/rest";
const execFileAsync = promisify(execFile);
export async function createPullRequestFromDiffs(config, input) {
    const workdir = await mkdtemp(join(tmpdir(), `ai-sdlc-${input.taskId}-`));
    const repoUrl = `https://x-access-token:${config.token}@github.com/${config.owner}/${config.repo}.git`;
    await git(["clone", repoUrl, "."], workdir);
    await git(["checkout", config.defaultBranch], workdir);
    await git(["pull", "origin", config.defaultBranch], workdir);
    await git(["checkout", "-b", input.devOutput.branch], workdir);
    for (const change of input.devOutput.changes) {
        const filePath = join(workdir, change.file);
        const dir = dirname(filePath);
        await mkdir(dir, { recursive: true });
        await writeFile(filePath, change.diff, "utf8");
    }
    /*
    for (const command of input.devOutput.commands) {
      try {
        await shell(command, workdir);
      } catch (err) {
        console.warn(`[GitHub Worker] Command failed but continuing: ${command}`, err);
      }
    }
    */
    await git(["add", "."], workdir);
    await git(["commit", "-m", `AI SDLC: ${input.taskId}`], workdir);
    const commitSha = (await git(["rev-parse", "HEAD"], workdir)).trim();
    await git(["push", "origin", input.devOutput.branch], workdir);
    const octokit = new Octokit({ auth: config.token });
    const pr = await octokit.pulls.create({
        owner: config.owner,
        repo: config.repo,
        title: `AI SDLC: ${input.idea.slice(0, 80)}`,
        head: input.devOutput.branch,
        base: config.defaultBranch,
        body: buildPullRequestBody(input)
    });
    return {
        url: pr.data.html_url,
        branch: input.devOutput.branch,
        commitSha
    };
}
function buildPullRequestBody(input) {
    const changes = input.devOutput.changes
        .map((change) => `- \`${change.file}\`: ${change.rationale}`)
        .join("\n");
    return [
        `Task: ${input.taskId}`,
        "",
        "Generated by AI SDLC MVP.",
        "",
        "Agent changes:",
        changes
    ].join("\n");
}
async function git(args, cwd) {
    const { stdout } = await execFileAsync("git", args, { cwd });
    return stdout;
}
async function shell(command, cwd) {
    const { stdout } = await execFileAsync("sh", ["-lc", command], { cwd });
    return stdout;
}
//# sourceMappingURL=github-worker.js.map